### ISSUE TITLE
Fish types configuration

### ISSUE THREAD

**Issue by wotnak** [wotnak/Rby#6]
Fish types will be now configured in separate yaml files `<fish_type_id>.yml` in `/fish/` directory.
Config file structure:
```yaml
# applies settings from this file on top of ones precofigured in preset (in `/fish_presets.yml`)
# type: string, optional
preset: "<preset_id>"
# name of the fish
# type: string
# can contain colors in & notation
name: "<name>"
# description of the fish
# type: array of strings
# can contain colors in & notation, each array element will be new line
lore:
  - "line_1"
  ...
# length or possible length range of the fish
# type: number or string in <number>..<number> notation
# if used as range then exact length will be determinned dynamically at catch 
length: min..max
# fish item
# type: item object, optional
# if omitted then minecraft:raw_cod
# used to drop catch item after sucessfull catch, in the future also used in gui
item:
  id: <item_id>
  # additionaly some field or fields to change item meta
# effect executed at sucessfull catch
# type: array of effect objects
# usually will be probably used to spawn fish catch item
effetcts:
  - id: <eff_id>
    # configuration object of the effect
    # type: mixed (whatever effect requires)
    attributes: {}
  ...
# conditions required to catch this fish type
# type: array of condition objects
# can for example restrict fish to specific biome, world, weather, elevation, require specific enchants etc.
conditions:
    # condition id
    # type: string
  - id: "<cond_id>"
    # condition configuration object
    # type: mixed (whatever specific condition requires)
    attributes: {}
    # allows to change this condition configuration depending on other conditions
    # type: modifier object
    # for example can be used to change condition settings depending on fishing rod enchants or weather conditions
    modifiers:
      - mod_id: <mod_id>
        mod_attributes: {}
        attributes: {}
  ...
```
